spring.application.name=harvestsyncbackend


spring.datasource.url=jdbc:mariadb://localhost:3306/harvesttrack_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=#GGMUsince2002

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver


# For production, consider using 'validate' alongside Liquibase or Flyway.
spring.jpa.hibernate.ddl-auto=update

# MariaDB dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
